POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "name": "Test User",
  "username": "testuser",
  "password": "testpassword",
  "email": "testEmail@5650.com"
}

###Login User
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpassword"
} 

### get all products/
GET http://localhost:5000/api/products/?category=All
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImlhdCI6MTc1NzM0MzkyMCwiZXhwIjoxNzU3MzQ3NTIwfQ.pmTGmANtMPet80cnfp9-bcuM0V11xZ6ynMF50Qy0QXo
